<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Aset;
use Carbon\Carbon;

class AsetSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $aset = [
            [
                'nama_aset' => 'X-Ray Machine Digital',
                'kode_aset' => 'AST-MED-001',
                'deskripsi' => 'Mesin X-Ray digital untuk pemeriksaan radiologi',
                'kategori' => 'Alat Medis',
                'supplier' => 'PT. Medika Sejahtera',
                'tanggal_pembelian' => Carbon::create(2022, 3, 15),
                'harga_perolehan' => 250000000,
                'nilai_saat_ini' => 200000000,
                'status_aset' => 'aktif',
                'lokasi' => 'Ruang Radiologi Lantai 2',
                'last_maintenance' => Carbon::create(2025, 10, 1),
                'next_maintenance' => Carbon::create(2026, 4, 1),
            ],
            [
                'nama_aset' => 'Ultrasonography (USG)',
                'kode_aset' => 'AST-MED-002',
                'deskripsi' => 'USG 4D untuk pemeriksaan kandungan dan organ dalam',
                'kategori' => 'Alat Medis',
                'supplier' => 'PT. Alkes Indonesia',
                'tanggal_pembelian' => Carbon::create(2021, 8, 20),
                'harga_perolehan' => 180000000,
                'nilai_saat_ini' => 135000000,
                'status_aset' => 'aktif',
                'lokasi' => 'Poliklinik Kebidanan Lantai 3',
                'last_maintenance' => Carbon::create(2025, 9, 15),
                'next_maintenance' => Carbon::create(2026, 3, 15),
            ],
            [
                'nama_aset' => 'Ventilator ICU',
                'kode_aset' => 'AST-MED-003',
                'deskripsi' => 'Ventilator untuk pasien ICU',
                'kategori' => 'Alat Medis',
                'supplier' => 'PT. Medical Equipment',
                'tanggal_pembelian' => Carbon::create(2023, 1, 10),
                'harga_perolehan' => 350000000,
                'nilai_saat_ini' => 300000000,
                'status_aset' => 'aktif',
                'lokasi' => 'Ruang ICU Lantai 4',
                'last_maintenance' => Carbon::create(2025, 11, 1),
                'next_maintenance' => Carbon::create(2025, 12, 1),
            ],
            [
                'nama_aset' => 'Electrocardiogram (ECG)',
                'kode_aset' => 'AST-MED-004',
                'deskripsi' => 'Mesin EKG 12 channel',
                'kategori' => 'Alat Medis',
                'supplier' => 'PT. Kardia Medika',
                'tanggal_pembelian' => Carbon::create(2022, 6, 5),
                'harga_perolehan' => 45000000,
                'nilai_saat_ini' => 35000000,
                'status_aset' => 'aktif',
                'lokasi' => 'Poliklinik Jantung Lantai 2',
                'last_maintenance' => Carbon::create(2025, 10, 10),
                'next_maintenance' => Carbon::create(2026, 4, 10),
            ],
            [
                'nama_aset' => 'Dental Chair Unit',
                'kode_aset' => 'AST-MED-005',
                'deskripsi' => 'Kursi dental lengkap dengan lampu dan alat',
                'kategori' => 'Alat Medis',
                'supplier' => 'PT. Dental Supplies',
                'tanggal_pembelian' => Carbon::create(2020, 11, 20),
                'harga_perolehan' => 75000000,
                'nilai_saat_ini' => 45000000,
                'status_aset' => 'aktif',
                'lokasi' => 'Klinik Gigi Lantai 1',
                'last_maintenance' => Carbon::create(2025, 8, 15),
                'next_maintenance' => Carbon::create(2026, 2, 15),
            ],
            [
                'nama_aset' => 'Server Komputer HP ProLiant',
                'kode_aset' => 'AST-ELK-001',
                'deskripsi' => 'Server untuk sistem informasi rumah sakit',
                'kategori' => 'Elektronik',
                'supplier' => 'PT. Komputer Persada',
                'tanggal_pembelian' => Carbon::create(2023, 5, 1),
                'harga_perolehan' => 120000000,
                'nilai_saat_ini' => 95000000,
                'status_aset' => 'aktif',
                'lokasi' => 'Ruang Server IT Lantai Basement',
                'last_maintenance' => Carbon::create(2025, 11, 10),
                'next_maintenance' => Carbon::create(2026, 5, 10),
            ],
            [
                'nama_aset' => 'AC Central Daikin 5 PK',
                'kode_aset' => 'AST-ELK-002',
                'deskripsi' => 'AC Central untuk ruang operasi',
                'kategori' => 'Elektronik',
                'supplier' => 'PT. Cool Tech',
                'tanggal_pembelian' => Carbon::create(2021, 4, 15),
                'harga_perolehan' => 65000000,
                'nilai_saat_ini' => 40000000,
                'status_aset' => 'aktif',
                'lokasi' => 'Ruang Operasi Lantai 3',
                'last_maintenance' => Carbon::create(2025, 10, 20),
                'next_maintenance' => Carbon::create(2026, 4, 20),
            ],
            [
                'nama_aset' => 'Meja Operasi Elektrik',
                'kode_aset' => 'AST-FUR-001',
                'deskripsi' => 'Meja operasi dengan sistem hidrolik elektrik',
                'kategori' => 'Furniture',
                'supplier' => 'PT. Medical Furniture',
                'tanggal_pembelian' => Carbon::create(2022, 9, 1),
                'harga_perolehan' => 95000000,
                'nilai_saat_ini' => 75000000,
                'status_aset' => 'aktif',
                'lokasi' => 'Ruang Operasi Utama Lantai 3',
                'last_maintenance' => Carbon::create(2025, 10, 5),
                'next_maintenance' => Carbon::create(2026, 4, 5),
            ],
            [
                'nama_aset' => 'Tempat Tidur Pasien Elektrik',
                'kode_aset' => 'AST-FUR-002',
                'deskripsi' => 'Tempat tidur pasien dengan pengatur posisi elektrik (10 unit)',
                'kategori' => 'Furniture',
                'supplier' => 'PT. Furniture Medis',
                'tanggal_pembelian' => Carbon::create(2023, 2, 10),
                'harga_perolehan' => 150000000,
                'nilai_saat_ini' => 120000000,
                'status_aset' => 'aktif',
                'lokasi' => 'Ruang Rawat Inap Lantai 5',
                'last_maintenance' => Carbon::create(2025, 11, 5),
                'next_maintenance' => Carbon::create(2026, 5, 5),
            ],
            [
                'nama_aset' => 'Ambulance Toyota Hiace',
                'kode_aset' => 'AST-VEH-001',
                'deskripsi' => 'Ambulance lengkap dengan peralatan medis darurat',
                'kategori' => 'Kendaraan',
                'supplier' => 'PT. Auto Medika',
                'tanggal_pembelian' => Carbon::create(2022, 7, 15),
                'harga_perolehan' => 450000000,
                'nilai_saat_ini' => 350000000,
                'status_aset' => 'aktif',
                'lokasi' => 'Parkir Ambulance Lantai Basement',
                'last_maintenance' => Carbon::create(2025, 11, 15),
                'next_maintenance' => Carbon::create(2025, 12, 15),
            ],
            // Obat-obatan dan Alat Medis Tambahan
            ['nama_aset' => 'Paracetamol 500mg', 'kode_aset' => 'OBT-001', 'deskripsi' => 'Obat demam dan nyeri', 'kategori' => 'Obat-obatan', 'supplier' => 'Industri Farmasi XYZ', 'tanggal_pembelian' => Carbon::create(2025, 1, 10), 'harga_perolehan' => 2500000, 'nilai_saat_ini' => 2000000, 'status_aset' => 'aktif', 'lokasi' => 'Apotek Lantai 1'],
            ['nama_aset' => 'Amoxicillin 500mg', 'kode_aset' => 'OBT-002', 'deskripsi' => 'Antibiotik untuk infeksi bakteri', 'kategori' => 'Obat-obatan', 'supplier' => 'Industri Farmasi ABC', 'tanggal_pembelian' => Carbon::create(2025, 1, 15), 'harga_perolehan' => 3500000, 'nilai_saat_ini' => 2800000, 'status_aset' => 'aktif', 'lokasi' => 'Apotek Lantai 1'],
            ['nama_aset' => 'Insulin Lantus 100 Unit/ml', 'kode_aset' => 'OBT-003', 'deskripsi' => 'Insulin untuk pasien diabetes', 'kategori' => 'Obat-obatan', 'supplier' => 'PT. Novo Nordisk', 'tanggal_pembelian' => Carbon::create(2024, 11, 20), 'harga_perolehan' => 8500000, 'nilai_saat_ini' => 7500000, 'status_aset' => 'aktif', 'lokasi' => 'Apotek Lantai 1'],
            ['nama_aset' => 'Antiseptik Betadine 10%', 'kode_aset' => 'OBT-004', 'deskripsi' => 'Antiseptik untuk sterilisasi luka', 'kategori' => 'Obat-obatan', 'supplier' => 'PT. Kimia Industri', 'tanggal_pembelian' => Carbon::create(2025, 1, 5), 'harga_perolehan' => 1500000, 'nilai_saat_ini' => 1200000, 'status_aset' => 'aktif', 'lokasi' => 'Apotek Lantai 1'],
            ['nama_aset' => 'Metformin 500mg', 'kode_aset' => 'OBT-005', 'deskripsi' => 'Obat diabetes tipe 2', 'kategori' => 'Obat-obatan', 'supplier' => 'Industri Farmasi XYZ', 'tanggal_pembelian' => Carbon::create(2025, 1, 8), 'harga_perolehan' => 2000000, 'nilai_saat_ini' => 1600000, 'status_aset' => 'aktif', 'lokasi' => 'Apotek Lantai 1'],
            ['nama_aset' => 'Omeprazole 20mg', 'kode_aset' => 'OBT-006', 'deskripsi' => 'Obat untuk asam lambung', 'kategori' => 'Obat-obatan', 'supplier' => 'Industri Farmasi DEF', 'tanggal_pembelian' => Carbon::create(2025, 1, 12), 'harga_perolehan' => 3000000, 'nilai_saat_ini' => 2400000, 'status_aset' => 'aktif', 'lokasi' => 'Apotek Lantai 1'],
            ['nama_aset' => 'Vitamin C 500mg', 'kode_aset' => 'OBT-007', 'deskripsi' => 'Vitamin untuk imunitas', 'kategori' => 'Obat-obatan', 'supplier' => 'PT. Vitamin Indonesia', 'tanggal_pembelian' => Carbon::create(2025, 1, 10), 'harga_perolehan' => 1800000, 'nilai_saat_ini' => 1400000, 'status_aset' => 'aktif', 'lokasi' => 'Apotek Lantai 1'],
            ['nama_aset' => 'Bandage Steril 5cm x 5m', 'kode_aset' => 'ALS-001', 'deskripsi' => 'Perban steril untuk perawatan luka', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Medika Supply', 'tanggal_pembelian' => Carbon::create(2025, 1, 1), 'harga_perolehan' => 500000, 'nilai_saat_ini' => 400000, 'status_aset' => 'aktif', 'lokasi' => 'Gudang Medis Lantai 2'],
            ['nama_aset' => 'Suntik Steril 3ml', 'kode_aset' => 'ALS-002', 'deskripsi' => 'Spuit medis steril ukuran 3ml', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Alat Medis Sejahtera', 'tanggal_pembelian' => Carbon::create(2025, 1, 3), 'harga_perolehan' => 750000, 'nilai_saat_ini' => 600000, 'status_aset' => 'aktif', 'lokasi' => 'Gudang Medis Lantai 2'],
            ['nama_aset' => 'Infus Set 18G', 'kode_aset' => 'ALS-003', 'deskripsi' => 'Set infus ukuran 18G', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Medical Supply', 'tanggal_pembelian' => Carbon::create(2025, 1, 5), 'harga_perolehan' => 1200000, 'nilai_saat_ini' => 1000000, 'status_aset' => 'aktif', 'lokasi' => 'Gudang Medis Lantai 2'],
            ['nama_aset' => 'Thermometer Digital', 'kode_aset' => 'ALS-004', 'deskripsi' => 'Termometer digital untuk pengukuran suhu', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Digital Medika', 'tanggal_pembelian' => Carbon::create(2024, 8, 15), 'harga_perolehan' => 850000, 'nilai_saat_ini' => 680000, 'status_aset' => 'aktif', 'lokasi' => 'Gudang Medis Lantai 2'],
            ['nama_aset' => 'Blood Pressure Monitor', 'kode_aset' => 'ALS-005', 'deskripsi' => 'Alat tensi meter digital', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Monitoring Kesehatan', 'tanggal_pembelian' => Carbon::create(2024, 9, 20), 'harga_perolehan' => 1500000, 'nilai_saat_ini' => 1200000, 'status_aset' => 'aktif', 'lokasi' => 'Gudang Medis Lantai 2'],
            ['nama_aset' => 'Pulse Oximeter', 'kode_aset' => 'ALS-006', 'deskripsi' => 'Alat pengukur oksigen darah dan denyut nadi', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Vital Sign Indonesia', 'tanggal_pembelian' => Carbon::create(2024, 10, 10), 'harga_perolehan' => 2500000, 'nilai_saat_ini' => 2000000, 'status_aset' => 'aktif', 'lokasi' => 'Gudang Medis Lantai 2'],
            ['nama_aset' => 'Sarung Tangan Medis Latex', 'kode_aset' => 'ALS-007', 'deskripsi' => 'Sarung tangan steril untuk medis (100 pasang)', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Protective Equipment', 'tanggal_pembelian' => Carbon::create(2025, 1, 2), 'harga_perolehan' => 600000, 'nilai_saat_ini' => 500000, 'status_aset' => 'aktif', 'lokasi' => 'Gudang Medis Lantai 2'],
            ['nama_aset' => 'Masker Medis N95', 'kode_aset' => 'ALS-008', 'deskripsi' => 'Masker medis N95 (50 buah)', 'kategori' => 'Alat Medis', 'supplier' => 'PT. PPE Supply', 'tanggal_pembelian' => Carbon::create(2025, 1, 4), 'harga_perolehan' => 1000000, 'nilai_saat_ini' => 800000, 'status_aset' => 'aktif', 'lokasi' => 'Gudang Medis Lantai 2'],
            ['nama_aset' => 'Kateter Urin', 'kode_aset' => 'ALS-009', 'deskripsi' => 'Kateter urin steril berbagai ukuran', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Catheter Indonesia', 'tanggal_pembelian' => Carbon::create(2024, 12, 20), 'harga_perolehan' => 2800000, 'nilai_saat_ini' => 2200000, 'status_aset' => 'aktif', 'lokasi' => 'Gudang Medis Lantai 2'],
            ['nama_aset' => 'Standar Infus IV Pole', 'kode_aset' => 'ALS-010', 'deskripsi' => 'Standar untuk menggantung infus', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Hospital Equipment', 'tanggal_pembelian' => Carbon::create(2023, 6, 1), 'harga_perolehan' => 3500000, 'nilai_saat_ini' => 2800000, 'status_aset' => 'aktif', 'lokasi' => 'Gudang Medis Lantai 2'],
            ['nama_aset' => 'Defibrillator AED', 'kode_aset' => 'ALS-011', 'deskripsi' => 'Alat defibrillator otomatis untuk kedaruratan', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Emergency Medical', 'tanggal_pembelian' => Carbon::create(2023, 3, 15), 'harga_perolehan' => 45000000, 'nilai_saat_ini' => 36000000, 'status_aset' => 'aktif', 'lokasi' => 'Ruang Gawat Darurat Lantai 1'],
            ['nama_aset' => 'Oksigen Tabung Besar', 'kode_aset' => 'ALS-012', 'deskripsi' => 'Tabung oksigen kapasitas besar untuk pasien', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Gas Medika', 'tanggal_pembelian' => Carbon::create(2024, 5, 1), 'harga_perolehan' => 8500000, 'nilai_saat_ini' => 7000000, 'status_aset' => 'aktif', 'lokasi' => 'Ruang ICU Lantai 4'],
            ['nama_aset' => 'Suction Pump (Penghisap)', 'kode_aset' => 'ALS-013', 'deskripsi' => 'Alat penghisap cairan dari saluran pernapasan', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Suction Medical', 'tanggal_pembelian' => Carbon::create(2024, 6, 10), 'harga_perolehan' => 5500000, 'nilai_saat_ini' => 4400000, 'status_aset' => 'aktif', 'lokasi' => 'Ruang ICU Lantai 4'],
            ['nama_aset' => 'Koleksi Darah Steril Tabung', 'kode_aset' => 'ALS-014', 'deskripsi' => 'Tabung pengambilan darah steril 5ml (100 pcs)', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Blood Collection', 'tanggal_pembelian' => Carbon::create(2025, 1, 6), 'harga_perolehan' => 1800000, 'nilai_saat_ini' => 1500000, 'status_aset' => 'aktif', 'lokasi' => 'Lab Lantai Basement'],
            ['nama_aset' => 'Slide Mikroskop Steril', 'kode_aset' => 'ALS-015', 'deskripsi' => 'Slide mikroskop steril untuk pemeriksaan', 'kategori' => 'Alat Medis', 'supplier' => 'PT. Lab Equipment', 'tanggal_pembelian' => Carbon::create(2025, 1, 7), 'harga_perolehan' => 1200000, 'nilai_saat_ini' => 1000000, 'status_aset' => 'aktif', 'lokasi' => 'Lab Lantai Basement'],
        ];

        foreach ($aset as $a) {
            Aset::create($a);
        }
    }
}
