<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Pegawai;
use Carbon\Carbon;

class PegawaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pegawai = [
            [
                'nama' => 'Dr. Ahmad Fauzi',
                'email' => 'ahmad.fauzi@carexis.com',
                'no_hp' => '081234567890',
                'alamat' => 'Jl. Merdeka No. 123, Jakarta',
                'jabatan' => 'Dokter Umum',
                'departemen' => 'Medis',
                'status_pegawai' => 'aktif',
                'tanggal_masuk' => Carbon::create(2020, 1, 15),
                'tanggal_lahir' => Carbon::create(1985, 5, 20),
                'jenis_kelamin' => 'laki-laki',
                'gaji_pokok' => 15000000,
                'user_id' => null,
            ],
            [
                'nama' => 'Dr. Siti Nurhaliza',
                'email' => 'siti.nurhaliza@carexis.com',
                'no_hp' => '081234567891',
                'alamat' => 'Jl. Sudirman No. 45, Jakarta',
                'jabatan' => 'Dokter Spesialis Anak',
                'departemen' => 'Medis',
                'status_pegawai' => 'aktif',
                'tanggal_masuk' => Carbon::create(2019, 3, 10),
                'tanggal_lahir' => Carbon::create(1987, 8, 15),
                'jenis_kelamin' => 'perempuan',
                'gaji_pokok' => 20000000,
                'user_id' => null,
            ],
            [
                'nama' => 'Budi Santoso',
                'email' => 'budi.santoso@carexis.com',
                'no_hp' => '081234567892',
                'alamat' => 'Jl. Thamrin No. 78, Jakarta',
                'jabatan' => 'Perawat',
                'departemen' => 'Medis',
                'status_pegawai' => 'aktif',
                'tanggal_masuk' => Carbon::create(2021, 6, 1),
                'tanggal_lahir' => Carbon::create(1990, 3, 12),
                'jenis_kelamin' => 'laki-laki',
                'gaji_pokok' => 7000000,
                'user_id' => null,
            ],
            [
                'nama' => 'Dewi Lestari',
                'email' => 'dewi.lestari@carexis.com',
                'no_hp' => '081234567893',
                'alamat' => 'Jl. Gatot Subroto No. 90, Jakarta',
                'jabatan' => 'Perawat',
                'departemen' => 'Medis',
                'status_pegawai' => 'aktif',
                'tanggal_masuk' => Carbon::create(2020, 9, 15),
                'tanggal_lahir' => Carbon::create(1992, 11, 25),
                'jenis_kelamin' => 'perempuan',
                'gaji_pokok' => 7000000,
                'user_id' => null,
            ],
            [
                'nama' => 'Rina Wijaya',
                'email' => 'rina.wijaya@carexis.com',
                'no_hp' => '081234567894',
                'alamat' => 'Jl. Kuningan No. 12, Jakarta',
                'jabatan' => 'Staff Administrasi',
                'departemen' => 'Administrasi',
                'status_pegawai' => 'aktif',
                'tanggal_masuk' => Carbon::create(2022, 2, 1),
                'tanggal_lahir' => Carbon::create(1995, 7, 8),
                'jenis_kelamin' => 'perempuan',
                'gaji_pokok' => 5000000,
                'user_id' => null,
            ],
            [
                'nama' => 'Andi Prasetyo',
                'email' => 'andi.prasetyo@carexis.com',
                'no_hp' => '081234567895',
                'alamat' => 'Jl. HR Rasuna Said No. 34, Jakarta',
                'jabatan' => 'Kepala HRD',
                'departemen' => 'Kepegawaian',
                'status_pegawai' => 'aktif',
                'tanggal_masuk' => Carbon::create(2018, 5, 20),
                'tanggal_lahir' => Carbon::create(1983, 4, 18),
                'jenis_kelamin' => 'laki-laki',
                'gaji_pokok' => 12000000,
                'user_id' => null,
            ],
            [
                'nama' => 'Maya Sari',
                'email' => 'maya.sari@carexis.com',
                'no_hp' => '081234567896',
                'alamat' => 'Jl. MT Haryono No. 56, Jakarta',
                'jabatan' => 'Apoteker',
                'departemen' => 'Farmasi',
                'status_pegawai' => 'aktif',
                'tanggal_masuk' => Carbon::create(2021, 10, 1),
                'tanggal_lahir' => Carbon::create(1989, 12, 5),
                'jenis_kelamin' => 'perempuan',
                'gaji_pokok' => 9000000,
                'user_id' => null,
            ],
            [
                'nama' => 'Rudi Hermawan',
                'email' => 'rudi.hermawan@carexis.com',
                'no_hp' => '081234567897',
                'alamat' => 'Jl. Casablanca No. 88, Jakarta',
                'jabatan' => 'IT Support',
                'departemen' => 'IT',
                'status_pegawai' => 'aktif',
                'tanggal_masuk' => Carbon::create(2022, 7, 15),
                'tanggal_lahir' => Carbon::create(1994, 2, 28),
                'jenis_kelamin' => 'laki-laki',
                'gaji_pokok' => 8000000,
                'user_id' => null,
            ],
            [
                'nama' => 'Fitri Handayani',
                'email' => 'fitri.handayani@carexis.com',
                'no_hp' => '081234567898',
                'alamat' => 'Jl. Menteng No. 23, Jakarta',
                'jabatan' => 'Customer Service',
                'departemen' => 'Administrasi',
                'status_pegawai' => 'cuti',
                'tanggal_masuk' => Carbon::create(2021, 4, 10),
                'tanggal_lahir' => Carbon::create(1993, 9, 14),
                'jenis_kelamin' => 'perempuan',
                'gaji_pokok' => 5500000,
                'user_id' => null,
            ],
            [
                'nama' => 'Agus Setiawan',
                'email' => 'agus.setiawan@carexis.com',
                'no_hp' => '081234567899',
                'alamat' => 'Jl. Kemang No. 67, Jakarta',
                'jabatan' => 'Security',
                'departemen' => 'Keamanan',
                'status_pegawai' => 'aktif',
                'tanggal_masuk' => Carbon::create(2019, 11, 1),
                'tanggal_lahir' => Carbon::create(1988, 6, 22),
                'jenis_kelamin' => 'laki-laki',
                'gaji_pokok' => 4500000,
                'user_id' => null,
            ],
            // Tambahan 40 pegawai
            ['nama' => 'Dr. Hendra Wijaya', 'email' => 'hendra.wijaya@carexis.com', 'no_hp' => '081234567900', 'alamat' => 'Jl. Blok M No. 10', 'jabatan' => 'Dokter Umum', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 1, 15), 'tanggal_lahir' => Carbon::create(1986, 3, 10), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 16000000, 'user_id' => null],
            ['nama' => 'dr. Eka Putri', 'email' => 'eka.putri@carexis.com', 'no_hp' => '081234567901', 'alamat' => 'Jl. Senayan No. 25', 'jabatan' => 'Dokter Spesialis', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2020, 2, 10), 'tanggal_lahir' => Carbon::create(1984, 7, 22), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 22000000, 'user_id' => null],
            ['nama' => 'Nurul Hidayah', 'email' => 'nurul.hidayah@carexis.com', 'no_hp' => '081234567902', 'alamat' => 'Jl. Kuningan No. 45', 'jabatan' => 'Perawat', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2022, 3, 1), 'tanggal_lahir' => Carbon::create(1995, 11, 8), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 7200000, 'user_id' => null],
            ['nama' => 'Bambang Hartono', 'email' => 'bambang.hartono@carexis.com', 'no_hp' => '081234567903', 'alamat' => 'Jl. Gatot Subroto No. 100', 'jabatan' => 'Perawat', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 5, 20), 'tanggal_lahir' => Carbon::create(1991, 4, 15), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 7200000, 'user_id' => null],
            ['nama' => 'Linda Susanti', 'email' => 'linda.susanti@carexis.com', 'no_hp' => '081234567904', 'alamat' => 'Jl. Menteng No. 55', 'jabatan' => 'Bidan', 'departemen' => 'Kebidanan', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2020, 8, 10), 'tanggal_lahir' => Carbon::create(1990, 9, 5), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 8000000, 'user_id' => null],
            ['nama' => 'Slamet Riyanto', 'email' => 'slamet.riyanto@carexis.com', 'no_hp' => '081234567905', 'alamat' => 'Jl. Ahmad Yani No. 30', 'jabatan' => 'Teknisi Lab', 'departemen' => 'Laboratorium', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 6, 1), 'tanggal_lahir' => Carbon::create(1992, 2, 12), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 6500000, 'user_id' => null],
            ['nama' => 'Tatik Wijaya', 'email' => 'tatik.wijaya@carexis.com', 'no_hp' => '081234567906', 'alamat' => 'Jl. Panglima No. 40', 'jabatan' => 'Staff Farmasi', 'departemen' => 'Farmasi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2022, 1, 15), 'tanggal_lahir' => Carbon::create(1996, 5, 20), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 6000000, 'user_id' => null],
            ['nama' => 'Cahyo Purnomo', 'email' => 'cahyo.purnomo@carexis.com', 'no_hp' => '081234567907', 'alamat' => 'Jl. Sudirman No. 78', 'jabatan' => 'Staff IT', 'departemen' => 'IT', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 9, 1), 'tanggal_lahir' => Carbon::create(1994, 8, 18), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 8500000, 'user_id' => null],
            ['nama' => 'Heni Kusumastuti', 'email' => 'heni.kusumastuti@carexis.com', 'no_hp' => '081234567908', 'alamat' => 'Jl. Hayam Wuruk No. 55', 'jabatan' => 'Admin Keuangan', 'departemen' => 'Keuangan', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2020, 4, 1), 'tanggal_lahir' => Carbon::create(1988, 10, 25), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 7500000, 'user_id' => null],
            ['nama' => 'Yudi Kristanto', 'email' => 'yudi.kristanto@carexis.com', 'no_hp' => '081234567909', 'alamat' => 'Jl. Ismail Marzuki No. 15', 'jabatan' => 'Manager Operasional', 'departemen' => 'Operasional', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2019, 7, 10), 'tanggal_lahir' => Carbon::create(1985, 1, 22), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 13000000, 'user_id' => null],
            ['nama' => 'Siti Rahma', 'email' => 'siti.rahma@carexis.com', 'no_hp' => '081234567910', 'alamat' => 'Jl. MT Haryono No. 88', 'jabatan' => 'Perawat', 'departemen' => 'Medis', 'status_pegawai' => 'cuti', 'tanggal_masuk' => Carbon::create(2021, 2, 15), 'tanggal_lahir' => Carbon::create(1993, 6, 30), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 7000000, 'user_id' => null],
            ['nama' => 'Arief Gunawan', 'email' => 'arief.gunawan@carexis.com', 'no_hp' => '081234567911', 'alamat' => 'Jl. Benda No. 25', 'jabatan' => 'Analis Kesehatan', 'departemen' => 'Laboratorium', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2020, 10, 1), 'tanggal_lahir' => Carbon::create(1989, 12, 3), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 6800000, 'user_id' => null],
            ['nama' => 'Wiwit Hariyanto', 'email' => 'wiwit.hariyanto@carexis.com', 'no_hp' => '081234567912', 'alamat' => 'Jl. Raya Bogor No. 60', 'jabatan' => 'Dokter Gigi', 'departemen' => 'Gigi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 4, 1), 'tanggal_lahir' => Carbon::create(1987, 9, 14), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 18000000, 'user_id' => null],
            ['nama' => 'Suryanto Budi', 'email' => 'suryanto.budi@carexis.com', 'no_hp' => '081234567913', 'alamat' => 'Jl. Casablanca No. 100', 'jabatan' => 'Petugas Kebersihan', 'departemen' => 'Operasional', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2022, 5, 1), 'tanggal_lahir' => Carbon::create(1996, 3, 20), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 4000000, 'user_id' => null],
            ['nama' => 'Endang Sulistyowati', 'email' => 'endang.sulistyowati@carexis.com', 'no_hp' => '081234567914', 'alamat' => 'Jl. Setiabudi No. 45', 'jabatan' => 'Nutrisionis', 'departemen' => 'Gizi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2020, 6, 15), 'tanggal_lahir' => Carbon::create(1991, 7, 11), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 7000000, 'user_id' => null],
            ['nama' => 'Rinto Soeprapto', 'email' => 'rinto.soeprapto@carexis.com', 'no_hp' => '081234567915', 'alamat' => 'Jl. Kuningan No. 88', 'jabatan' => 'Dokter', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2019, 9, 1), 'tanggal_lahir' => Carbon::create(1984, 11, 5), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 17000000, 'user_id' => null],
            ['nama' => 'Susi Handayani', 'email' => 'susi.handayani@carexis.com', 'no_hp' => '081234567916', 'alamat' => 'Jl. Imam Bonjol No. 30', 'jabatan' => 'Radiografer', 'departemen' => 'Radiologi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 3, 1), 'tanggal_lahir' => Carbon::create(1993, 2, 16), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 8000000, 'user_id' => null],
            ['nama' => 'Dani Hermawan', 'email' => 'dani.hermawan@carexis.com', 'no_hp' => '081234567917', 'alamat' => 'Jl. Diponegoro No. 50', 'jabatan' => 'Maintenance', 'departemen' => 'Teknik', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2020, 8, 1), 'tanggal_lahir' => Carbon::create(1990, 5, 8), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 5500000, 'user_id' => null],
            ['nama' => 'Komala Sari', 'email' => 'komala.sari@carexis.com', 'no_hp' => '081234567918', 'alamat' => 'Jl. Raden Saleh No. 25', 'jabatan' => 'Resepsionis', 'departemen' => 'Administrasi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 7, 1), 'tanggal_lahir' => Carbon::create(1997, 1, 12), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 5000000, 'user_id' => null],
            ['nama' => 'Prabowo Aji', 'email' => 'prabowo.aji@carexis.com', 'no_hp' => '081234567919', 'alamat' => 'Jl. Kunciran No. 35', 'jabatan' => 'Driver', 'departemen' => 'Operasional', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2022, 2, 1), 'tanggal_lahir' => Carbon::create(1994, 8, 24), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 4800000, 'user_id' => null],
            ['nama' => 'Ningsih Dwi', 'email' => 'ningsih.dwi@carexis.com', 'no_hp' => '081234567920', 'alamat' => 'Jl. Medlindsari No. 15', 'jabatan' => 'Asisten Medis', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 8, 15), 'tanggal_lahir' => Carbon::create(1995, 4, 27), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 6500000, 'user_id' => null],
            ['nama' => 'Tomi Setiawan', 'email' => 'tomi.setiawan@carexis.com', 'no_hp' => '081234567921', 'alamat' => 'Jl. Terogong No. 40', 'jabatan' => 'Admin Medis', 'departemen' => 'Administrasi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2020, 9, 1), 'tanggal_lahir' => Carbon::create(1992, 10, 30), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 6000000, 'user_id' => null],
            ['nama' => 'Rini Setyowati', 'email' => 'rini.setyowati@carexis.com', 'no_hp' => '081234567922', 'alamat' => 'Jl. Raya Kebon Jeruk', 'jabatan' => 'Cleaning Service', 'departemen' => 'Operasional', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2022, 3, 15), 'tanggal_lahir' => Carbon::create(1996, 6, 5), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 4000000, 'user_id' => null],
            ['nama' => 'Gunawan Pratama', 'email' => 'gunawan.pratama@carexis.com', 'no_hp' => '081234567923', 'alamat' => 'Jl. Kompleks Kemakmuran', 'jabatan' => 'Security Officer', 'departemen' => 'Keamanan', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 10, 1), 'tanggal_lahir' => Carbon::create(1989, 9, 18), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 5000000, 'user_id' => null],
            ['nama' => 'Ani Suwarto', 'email' => 'ani.suwarto@carexis.com', 'no_hp' => '081234567924', 'alamat' => 'Jl. Pasar Minggu No. 20', 'jabatan' => 'Koordinator Asuhan', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2020, 11, 1), 'tanggal_lahir' => Carbon::create(1990, 8, 22), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 9000000, 'user_id' => null],
            ['nama' => 'Bintang Wijaya', 'email' => 'bintang.wijaya@carexis.com', 'no_hp' => '081234567925', 'alamat' => 'Jl. Kemang No. 45', 'jabatan' => 'Dokter', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2019, 4, 15), 'tanggal_lahir' => Carbon::create(1983, 12, 10), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 19000000, 'user_id' => null],
            ['nama' => 'Dewita Salsabila', 'email' => 'dewita.salsabila@carexis.com', 'no_hp' => '081234567926', 'alamat' => 'Jl. Gatot No. 65', 'jabatan' => 'Perawat', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2022, 1, 10), 'tanggal_lahir' => Carbon::create(1996, 11, 3), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 7000000, 'user_id' => null],
            ['nama' => 'Endra Marpaung', 'email' => 'endra.marpaung@carexis.com', 'no_hp' => '081234567927', 'alamat' => 'Jl. Taman Ismail', 'jabatan' => 'Teknisi Medis', 'departemen' => 'Teknik', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 5, 15), 'tanggal_lahir' => Carbon::create(1993, 3, 25), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 7500000, 'user_id' => null],
            ['nama' => 'Friska Amelia', 'email' => 'friska.amelia@carexis.com', 'no_hp' => '081234567928', 'alamat' => 'Jl. Setiabudi No. 80', 'jabatan' => 'Fisioterapis', 'departemen' => 'Rehabilitasi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 6, 1), 'tanggal_lahir' => Carbon::create(1994, 7, 8), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 8500000, 'user_id' => null],
            ['nama' => 'Heru Kristianto', 'email' => 'heru.kristianto@carexis.com', 'no_hp' => '081234567929', 'alamat' => 'Jl. Mertani No. 30', 'jabatan' => 'Apoteker', 'departemen' => 'Farmasi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2020, 7, 1), 'tanggal_lahir' => Carbon::create(1988, 5, 14), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 9500000, 'user_id' => null],
            ['nama' => 'Ika Mursitowati', 'email' => 'ika.mursitowati@carexis.com', 'no_hp' => '081234567930', 'alamat' => 'Jl. Jend Sudirman No. 12', 'jabatan' => 'Perawat', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 9, 15), 'tanggal_lahir' => Carbon::create(1995, 10, 19), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 7000000, 'user_id' => null],
            ['nama' => 'Joko Supriyanto', 'email' => 'joko.supriyanto@carexis.com', 'no_hp' => '081234567931', 'alamat' => 'Jl. Benda No. 88', 'jabatan' => 'Dokumentasi Medis', 'departemen' => 'Administrasi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2020, 10, 15), 'tanggal_lahir' => Carbon::create(1989, 11, 2), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 6000000, 'user_id' => null],
            ['nama' => 'Kusuma Dewi', 'email' => 'kusuma.dewi@carexis.com', 'no_hp' => '081234567932', 'alamat' => 'Jl. Blok M No. 22', 'jabatan' => 'Perawat', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 11, 1), 'tanggal_lahir' => Carbon::create(1996, 2, 28), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 7000000, 'user_id' => null],
            ['nama' => 'Lanang Hardianto', 'email' => 'lanang.hardianto@carexis.com', 'no_hp' => '081234567933', 'alamat' => 'Jl. Terogong No. 55', 'jabatan' => 'Analis Laboratorium', 'departemen' => 'Laboratorium', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2020, 12, 1), 'tanggal_lahir' => Carbon::create(1991, 4, 10), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 6800000, 'user_id' => null],
            ['nama' => 'Monica Sariasih', 'email' => 'monica.sariasih@carexis.com', 'no_hp' => '081234567934', 'alamat' => 'Jl. Salemba Raya', 'jabatan' => 'Perawat', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 12, 15), 'tanggal_lahir' => Carbon::create(1997, 8, 5), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 7000000, 'user_id' => null],
            ['nama' => 'Nendra Pratama', 'email' => 'nendra.pratama@carexis.com', 'no_hp' => '081234567935', 'alamat' => 'Jl. Raya Pondok Gede', 'jabatan' => 'Teknisi Laboratorium', 'departemen' => 'Laboratorium', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2022, 1, 20), 'tanggal_lahir' => Carbon::create(1997, 9, 14), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 6000000, 'user_id' => null],
            ['nama' => 'Oktaviana Putri', 'email' => 'oktaviana.putri@carexis.com', 'no_hp' => '081234567936', 'alamat' => 'Jl. Kemang Utara No. 5', 'jabatan' => 'Asisten Apoteker', 'departemen' => 'Farmasi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2022, 2, 15), 'tanggal_lahir' => Carbon::create(1997, 3, 22), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 5500000, 'user_id' => null],
            ['nama' => 'Pia Handoko', 'email' => 'pia.handoko@carexis.com', 'no_hp' => '081234567937', 'alamat' => 'Jl. Jatinegara Barat', 'jabatan' => 'Staff Administrasi', 'departemen' => 'Administrasi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 3, 20), 'tanggal_lahir' => Carbon::create(1994, 12, 8), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 5500000, 'user_id' => null],
            ['nama' => 'Reno Budiono', 'email' => 'reno.budiono@carexis.com', 'no_hp' => '081234567938', 'alamat' => 'Jl. Pramuka No. 50', 'jabatan' => 'Perawat', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 4, 10), 'tanggal_lahir' => Carbon::create(1993, 1, 15), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 7000000, 'user_id' => null],
            ['nama' => 'Sinta Rahayu', 'email' => 'sinta.rahayu@carexis.com', 'no_hp' => '081234567939', 'alamat' => 'Jl. Medansatria No. 25', 'jabatan' => 'Kamar Operasi', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2020, 5, 1), 'tanggal_lahir' => Carbon::create(1989, 2, 20), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 8000000, 'user_id' => null],
            ['nama' => 'Tria Gunawan', 'email' => 'tria.gunawan@carexis.com', 'no_hp' => '081234567940', 'alamat' => 'Jl. Merdeka Utara No. 10', 'jabatan' => 'Perawat', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 5, 25), 'tanggal_lahir' => Carbon::create(1995, 7, 11), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 7000000, 'user_id' => null],
            ['nama' => 'Ujang Supratman', 'email' => 'ujang.supratman@carexis.com', 'no_hp' => '081234567941', 'alamat' => 'Jl. Bendungan Hilir No. 30', 'jabatan' => 'Operator Radiologi', 'departemen' => 'Radiologi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 6, 15), 'tanggal_lahir' => Carbon::create(1992, 8, 9), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 7500000, 'user_id' => null],
            ['nama' => 'Vicky Setyo', 'email' => 'vicky.setyo@carexis.com', 'no_hp' => '081234567942', 'alamat' => 'Jl. Matraman Raya No. 15', 'jabatan' => 'Perawat', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2022, 3, 1), 'tanggal_lahir' => Carbon::create(1996, 9, 7), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 7000000, 'user_id' => null],
            ['nama' => 'Wahyu Siburian', 'email' => 'wahyu.siburian@carexis.com', 'no_hp' => '081234567943', 'alamat' => 'Jl. Cikini No. 70', 'jabatan' => 'Staff Medis', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 7, 10), 'tanggal_lahir' => Carbon::create(1993, 10, 16), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 6500000, 'user_id' => null],
            ['nama' => 'Xenia Wulandari', 'email' => 'xenia.wulandari@carexis.com', 'no_hp' => '081234567944', 'alamat' => 'Jl. Veteran No. 45', 'jabatan' => 'Admin Farmasi', 'departemen' => 'Farmasi', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 8, 20), 'tanggal_lahir' => Carbon::create(1995, 11, 29), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 5800000, 'user_id' => null],
            ['nama' => 'Yusuf Irawan', 'email' => 'yusuf.irawan@carexis.com', 'no_hp' => '081234567945', 'alamat' => 'Jl. Letjen S. Parman No. 50', 'jabatan' => 'Perawat', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2021, 9, 5), 'tanggal_lahir' => Carbon::create(1994, 4, 12), 'jenis_kelamin' => 'laki-laki', 'gaji_pokok' => 7000000, 'user_id' => null],
            ['nama' => 'Zahra Khaira', 'email' => 'zahra.khaira@carexis.com', 'no_hp' => '081234567946', 'alamat' => 'Jl. Kepala Batu No. 25', 'jabatan' => 'Perawat', 'departemen' => 'Medis', 'status_pegawai' => 'aktif', 'tanggal_masuk' => Carbon::create(2022, 4, 1), 'tanggal_lahir' => Carbon::create(1997, 5, 18), 'jenis_kelamin' => 'perempuan', 'gaji_pokok' => 7000000, 'user_id' => null],
        ];

        foreach ($pegawai as $p) {
            Pegawai::create($p);
        }
    }
}
